### ISSUE TITLE
Elevated Session Error

### ISSUE THREAD

**Issue by bfjare** [kinoli/groupie#3]
Getting this issue when registering a new user
```
Unauthorized
This action may only be performed with an elevated session.
```

This is the form I am using
```
<form method="post" accept-charset="UTF-8">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="users/save-user">
    {{ redirectInput('') }}
    {% macro errorList(errors) %}
    {% if errors %}
        <ul class="errors">
            {% for error in errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% endmacro %}
    {% from _self import errorList %}
    <input id="groups" type="text" name="groups[]" value="2">
    <input id="firstName" type="text" name="firstName" value="">
    <input id="lastName" type="text" name="lastName" value="">
    <input id="username" type="text" name="username" value="">
    <input id="email" type="text" name="email" value="">
    <input id="password" type="password" name="password" value="">
     <input type="submit" value="Register">
</form>
```
Plugin currently is set with full group access.
I've tried it with the group handle and id, I see craft3 does it by id in the control panel.
When the form is submitted the user is created but not assigned to any groups. 
I feel like its a permissions error but I cant find anything missing. Especially with it creating the user succesfully.

Craft Version: 3.1.3

**Comment by kinoli** [comment]
I will look into this but I noticed your value param on password has 3 double quotes instead of 2. Not sure if that would make a difference, but you should fix it anyways.

**Comment by kinoli** [comment]
I just tried your form in a local craft install and it works fine for me and adds the users to their selected groups. The issue must be a setting. Have you turned on “Allow Public Registration” in the backend user settings?

**Comment by bfjare** [comment]
I'm sure its a setting issue just can't find what it is.  I do have that setting on.

<img width="405" alt="screen shot 2019-01-25 at 9 13 48 am" src="https://user-images.githubusercontent.com/11744681/51757839-abff0e00-2081-11e9-9f78-9450387dbe61.png">

The person registering the user is logged in would that create an issue?

**Comment by kinoli** [comment]
Can you try adding this to config/general.php?

```
'elevatedSessionDuration' => 0
```

I don't see this as a permanent fix and I will look into this further when I get some time. Hopefully soon.

**Comment by bfjare** [comment]
Confirming this works with the config edit
