### ISSUE TITLE
Add guidance to documentation on what value group fields should have

### ISSUE THREAD

**Issue by iamkeir** [kinoli/groupie#6]
Hi there - thanks for the awesome plugin.

Just thought it might be useful to add to the documentation that any `groups[]` field within the `/users/save-user` form should contain the group ID integer, which you can find in the URL when looking at a particular group in the Craft admin, e.g. `http://yoursite.com/admin/settings/users/groups/4`

:)

**Comment by kinoli** [comment]
Ill get that added. Thanks for the suggestion.

**Comment by brimby** [comment]
Seconded. The existence of this issue saved me some frustration for sure.

**Comment by kinoli-opi** [comment]
Sorry for the delay on this, the readme has been updated, It should have all the details you need now.

**Comment by kinoli** [comment]
Sorry for the delay on this, the readme has been updated, It should have all the details you need now.
