### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [kinoli/groupie#9]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `kinoli\groupie\assetbundles\Groupie\GroupieAsset` located in `./vendor/kinoli/groupie/src/assetbundles/groupie/GroupieAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/groupie src/assetbundles/Groupie
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by kinoli** [comment]
Thanks for the heads up. This has been fixed.

**Comment by brandonkelly** [comment]
I’ve verified that the fix worked, however your `1.0.5` tag hasn’t been picked up by Packagist or the Craft Plugin Store, because it conflicts with the `version` in composer.json:

https://github.com/kinoli/groupie/blob/138fc2cba97f514818afddc07728b000cc1dd42e/composer.json#L5

**Comment by kinoli** [comment]
My bad, fixed.
